# Generated by Django 5.0.4 on 2024-06-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_course_course_code_course_credits_course_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='grade',
        ),
    ]
