# Generated by Django 5.0.4 on 2024-08-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_newstudentregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstudentregistration',
            name='name',
        ),
        migrations.AddField(
            model_name='newstudentregistration',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newstudentregistration',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newstudentregistration',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='semester',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='student_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='student_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular')], max_length=50),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='year_level',
            field=models.IntegerField(),
        ),
    ]
