# Generated by Django 5.0.4 on 2024-08-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_newstudentregistration_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudentregistration',
            name='student_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
