# Generated by Django 5.0.4 on 2024-08-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_newstudentregistration_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudentregistration',
            name='course',
            field=models.CharField(choices=[('bsit', 'Bsit'), ('cs', 'Cs'), ('crim', 'Crim')], max_length=100),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='semester',
            field=models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='year_level',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')]),
        ),
    ]
