# Generated by Django 6.0 on 2025-12-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_newstudentregistration_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudentregistration',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='course',
            field=models.CharField(choices=[('bsit', 'BSIT'), ('cs', 'BSCS'), ('bshm', 'BSHM'), ('crim', 'BSCRIM'), ('bsp', 'BSP'), ('bsed', 'BSEd')], max_length=100),
        ),
    ]
